In [1]:
am-import pandas as pd
import numpy as np

In [2]:
path = 'smallerdata.csv' #this is just the full dataset without some of the columns as shown below
data = pd.read_csv(path)
data

,dns_qdomainname,shieldid,day,num_clients,num_responses,num_dns_qname
0,*google.com,myakitjit,2022-10-02,1,2,1
1,*google.com,myakitjit,2022-10-03,1,2,1
2,*google.com,nimchulha,2022-10-04,1,2,1
3,*google.com,thewseanwi,2022-10-10,1,1,1
4,*google.com,nimchulha,2022-10-11,1,110,1
...,...,...,...,...,...,...
19309835,zzzzzzz1000.ph,haddomyev,2022-12-15,1,1,1
19309836,zzzzzzzzz.com,haddomyev,2022-12-29,1,2,1
19309837,zzzzzzzzzzzzzzzzzz.com,haddomyev,2022-12-28,1,2,1
19309838,zzzzzzzzzzzzzzzzzz.com,haddomyev,2023-01-05,1,2,1
19309839,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...,haddomyev,2023-01-19,1,1,1

In [3]:
pivot_table = data.pivot_table(values = 'shieldid', index = ['dns_qdomainname', 'day'], columns = None, aggfunc = 'nunique')

In [7]:
pivot_table.reset_index(inplace = True)

In [11]:
counts = pivot_table.groupby('dns_qdomainname')['day'].nunique()

In [99]:
filtered_df = pivot_table.loc[pivot_table['dns_qdomainname'].isin(counts[counts <= 7].index)] #change the number "7" for how many days you want this domain_name to show up in the dataset

In [100]:
filtered_df

,dns_qdomainname,day,shieldid
19,0--0--0.de,2023-01-05,1
20,0-0.au,2022-12-29,1
21,0-0.net.ph,2022-12-15,1
22,0-00-000-0000.com,2022-12-29,1
23,0-002.ph,2023-01-19,1
...,...,...,...
14440739,zzzzzzz1000.ph,2022-12-15,1
14440740,zzzzzzzzz.com,2022-12-29,1
14440741,zzzzzzzzzzzzzzzzzz.com,2022-12-28,1
14440742,zzzzzzzzzzzzzzzzzz.com,2023-01-05,1
14440743,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz...,2023-01-19,1

In [106]:
filtered_df[filtered_df.shieldid > 5] # change "3" to see domains with more or less than 5 unique shieldids

                    dns_qdomainname         day  shieldid
806018                 amsa-trk.com  2022-12-20         6
1130232               astra-mag.com  2022-10-05        10
1130233               astra-mag.com  2022-10-06         8
1604148                beside.media  2023-01-04        10
1604149                beside.media  2023-01-05         6
1661456                     bger.ch  2022-10-03         7
1975719              braincharm.com  2022-10-03         6
2560079          checktoprotect.org  2022-11-03         6
3722503                   donda.org  2022-10-27         7
3731018                doodles.goog  2022-10-31        12
3756489               downin.africa  2022-10-04         6
4022944               efile4biz.com  2023-01-20         6
4204234       entertainmentmesh.com  2022-10-31         6
4660630           fishingstatus.com  2022-10-17         6
4740375           fmbetterforms.com  2022-10-03         6
4771365          footballzebras.com  2022-10-25         6
6444536                iranwire.com  2022-12-13         6
7088392                   knsso.com  2022-11-18         8
7662820             lorettalynn.com  2022-10-04         7
8531090         movementdespise.com  2022-11-03         6
8968651                    nhpr.org  2022-11-09         6
9561047   paramountpressexpress.com  2022-10-12         7
9649115                 pcsoweb.com  2022-10-03         7
10440295          realclearwire.com  2022-11-09         6
11014980       savesmarterdaily.com  2022-10-18         6
11030256                  sbsun.com  2022-10-03         6
11207815          sensualsmiles.com  2022-11-01         6
11356717          shoplium-shop.com  2022-10-03         6
11371013               shotshow.org  2023-01-17         6
11813543                srmails.com  2022-10-03         6
12354213                 telnyx.com  2023-01-20         6
12460371    thecatholictraveler.com  2022-10-06         9
13035220              turismofvg.it  2022-10-06         8

In [87]:
anomalies = filtered_df[filtered_df.shieldid > 5].set_index('day')

In [88]:
anomalies

                      dns_qdomainname  shieldid
day
2022-12-20               amsa-trk.com         6
2022-10-05              astra-mag.com        10
2022-10-06              astra-mag.com         8
2023-01-04               beside.media        10
2023-01-05               beside.media         6
2022-10-03                    bger.ch         7
2022-10-03             braincharm.com         6
2022-11-03         checktoprotect.org         6
2022-10-27                  donda.org         7
2022-10-31               doodles.goog        12
2022-10-04              downin.africa         6
2023-01-20              efile4biz.com         6
2022-10-31      entertainmentmesh.com         6
2022-10-17          fishingstatus.com         6
2022-10-03          fmbetterforms.com         6
2022-10-25         footballzebras.com         6
2022-12-13               iranwire.com         6
2022-11-18                  knsso.com         8
2022-10-04            lorettalynn.com         7
2022-11-03        movementdespise.com         6
2022-11-09                   nhpr.org         6
2022-10-12  paramountpressexpress.com         7
2022-10-03                pcsoweb.com         7
2022-11-09          realclearwire.com         6
2022-10-18       savesmarterdaily.com         6
2022-10-03                  sbsun.com         6
2022-11-01          sensualsmiles.com         6
2022-10-03          shoplium-shop.com         6
2023-01-17               shotshow.org         6
2022-10-03                srmails.com         6
2023-01-20                 telnyx.com         6
2022-10-06    thecatholictraveler.com         9
2022-10-06              turismofvg.it         8

In [ ]:
# Now hopefully we can use this to help label anomalies and start to do some ML!